services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: <CHANGE_ME>
      POSTGRES_PASSWORD: <CHANGE_ME>
      POSTGRES_DB: <CHANGE_ME>
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: